version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27018:27017
    volumes:
      - ./mongo:/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: *****
      